version: 2.0

jobs:
  ubuntu-dev:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            ./.circleci/build_image.sh ubuntu-dev/ubuntu-dev.dockerfile janitortechnology/ubuntu-dev
            docker save janitortechnology/ubuntu-dev -o ubuntu-dev.tar
      - persist_to_workspace:
          root: .
          paths:
            - ubuntu-dev.tar

  chromium:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i ubuntu-dev.tar
            ./.circleci/build_image.sh chromium/chromium.dockerfile janitortechnology/chromium
          no_output_timeout: 90m

  fennec:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i ubuntu-dev.tar
            ./.circleci/build_image.sh fennec/fennec.dockerfile janitortechnology/fennec
          no_output_timeout: 30m

  firefox-git:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i ubuntu-dev.tar
            ./.circleci/build_image.sh firefox/firefox-git.dockerfile janitortechnology/firefox
          no_output_timeout: 30m

  firefox-hg:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i ubuntu-dev.tar
            ./.circleci/build_image.sh firefox/firefox-hg.dockerfile janitortechnology/firefox-hg
          no_output_timeout: 30m

  kde:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i ubuntu-dev.tar
            git submodule update --rebase --remote kde
            ./.circleci/build_image.sh kde/dockerfile janitortechnology/kde

  rust:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i ubuntu-dev.tar
            ./.circleci/build_image.sh rust/rust.dockerfile janitortechnology/rust
          no_output_timeout: 30m

  servo:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i ubuntu-dev.tar
            ./.circleci/build_image.sh servo/servo.dockerfile janitortechnology/servo
          no_output_timeout: 30m

  thunderbird:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            docker load -i ubuntu-dev.tar
            ./.circleci/build_image.sh thunderbird/thunderbird.dockerfile janitortechnology/thunderbird
          no_output_timeout: 30m

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - ubuntu-dev
      - chromium:
          requires:
            - ubuntu-dev
      - fennec:
          requires:
            - ubuntu-dev
      - firefox-git:
          requires:
            - ubuntu-dev
      - firefox-hg:
          requires:
            - ubuntu-dev
      - kde:
          requires:
            - ubuntu-dev
      - rust:
          requires:
            - ubuntu-dev
      - servo:
          requires:
            - ubuntu-dev
      - thunderbird:
          requires:
            - ubuntu-dev
